### ISSUE TITLE
Examples in README 404

### ISSUE THREAD

**Issue by lizadaly** [oreillymedia/thebe#37]
None of these links currently work, from the README:

"Here are a some relatively simple examples and a more complicated one."

Have the examples moved elsewhere?

**Comment by rgbkrk** [comment]
I fixed these in https://github.com/oreillymedia/thebe/pull/32, waiting on @zischwartz to merge. :wink:

**Comment by zischwartz** [comment]
Sorry about that!

**Comment by lizadaly** [comment]
Last one's still not found: https://oreillymedia.github.io/thebe/examples/built_sans_runnable_attr.html

**Comment by zischwartz** [comment]
Doh! Thanks. Fixed.
